### ISSUE TITLE
Collision errors

### ISSUE THREAD

**Issue by Cleroth** [Blindhawk/Platernia#10]
Dashing right on the ceiling while going into another ceiling makes the player hit the corner of the second ceiling. Video: http://img.cleroth.com/2015-05-20_16-51-25.mp4

**Comment by Cleroth** [comment]
Setting fallSpeed to positive amount makes it easier to reproduce.

**Comment by Cleroth** [comment]
http://img.cleroth.com/2015-05-21_16-26-11.mp4

**Comment by Cleroth** [comment]
This still happens when dashing right on the ceiling. It'll just stay in place.

**Comment by Blindhawk** [comment]
Cannot reproduce.
