### ISSUE TITLE
Character ground acceleration

### ISSUE THREAD

**Issue by Cleroth** [Blindhawk/Platernia#14]
Add a variable `accelx` to accelerate the character when on the ground until he reaches `vx` (note that there is no friction on the ground). There is no need for acceleration in the air as the maniability in the air is fine right now with the 3% friction.

**Comment by Blindhawk** [comment]
vx is ground acceleration per tick.

**Comment by Cleroth** [comment]
No, it isn't. It seems to be velocity per... tick.
I've set vx to  20 and maxvx to 2000000 and I don't really get past 20 speed.

**Comment by Cleroth** [comment]
I've looked at the code and it's definitely not acceleration.
Acceleration should add a value to v_._x every tick. vx just sets it.

**Comment by Blindhawk** [comment]
<p><code>
                        if (movingLeft_) {
				obj_.setVX(obj_.getVX() - getVX());
			}
			if (movingRight_) {
				obj_.setVX(obj_.getVX() + getVX());
			}
</code></p>

**Comment by Cleroth** [comment]
How come it's not accelerating towards maxvx then?

**Comment by Cleroth** [comment]
Sigh, I've explained what I want, and that because of the friction thing it can't be achieved, but whatever. Obviously it's invalid that I can't achieve what I want with the current system!

**Comment by Cleroth** [comment]
Having full friction makes it impossible to achieve acceleration using that variable. And I don't want to have less than full friction on the ground.

**Comment by Cleroth** [comment]
`velocity += acceleration - friction*velocity`

This is the equation for moving objects. As you can see, you have only provided friction and velocity, not acceleration.

**Comment by Cleroth** [comment]
So maybe make friction become 100% when the player is grounded and not pressing any direction then?
