### ISSUE TITLE
Restarting a level and jumping without moving left or right won't allow you to double jump

### ISSUE THREAD

**Issue by Cleroth** [Blindhawk/Platernia#53]

**Comment by Cleroth** [comment]
It thinks the player is in the air

**Comment by Blindhawk** [comment]
It IS in the air

**Comment by Cleroth** [comment]
NOT MY PROBLEM.
I put the player directly on the tile above where it should be standing. What else should I do

**Comment by Blindhawk** [comment]
Can make invisible ticks of gravity at player placement till grounded

**Comment by Cleroth** [comment]
No, because I'll  want some levels to start in the air.

**Comment by Cleroth** [comment]
Why is it in the air? I don't get it. Align the player to the tile by its bottom
